Global:
  aug: true
  checkpoints: ../save_models/
  dict_path: tumbocr/dict/en_dict/en_dict.txt
  epochs: 100
  gpu: null
  model_name:  ResNet-en-ctc
  out_seq_len: 30
  pretrained: "../save_models/ResNet-en-ctc-0-19999.pth"
  print_feq: 10
  resume: false
  save_iter: 20000
  start_epoch: 0
  val_iter: 10000
  loss : sar
  balanced_bsz: 128 # if balanced_batch_size > 0 using BalancedDataParallel
Model:
  arch: SAR
  backbone: ResNet # [MobileNetV3, ResNet]
  feature_layers: 512 #MobileNetV3 480, ResNet 512
  hidden_dim_de: 256
  embedding_size: 256
  hidden_dim: 256
  hidden_dim_de: 256
  num_layers: 2
Optimizer:
  name: adam
  lr: 0.0008
  momentum: 0.9
  weight_decay: 0.0
  scheduler: 
    name: step
    milestones_list: [5, 15, 25]
    gamma: 0.1
  warmup: -1
  warmup_lr: 1.0e-06
Train:
  rand_aug: true
  text_aug: true
  balanced_pow: -1
  batch_size: 1248
  drop_last: true
  image_shape: [48, 160]
  shuffle: true
  train_path: /data/remote/ocr_data/OCR_GT/90k_SynthText_SynthAdd.txt
  workers: 32
Val:
  batch_size: 1248
  drop_last: true
  image_shape: [48, 160]
  shuffle: true
  val_path: /data/remote/ocr_data/OCR_GT/openReal/icdar2015_Test.txt
  workers: 32
