Global:
  aug: true
  checkpoints: ../save_models/
  dict_path: tumbocr/dict/en_dict/en_dict.txt
  epochs: 100
  gpu: null
  model_name: myModel-MobileNetV3L-en
  out_seq_len: 40
  pretrained: ""
  print_feq: 10
  resume: false
  save_iter: 10000
  start_epoch: 0
  val_iter: 10000
  loss : ctc
Model:
  arch: myModel
  tps: 
    name: null
    # num_fiducial: 20
  backbone: 
    name: MobileNetV3 # [MobileNetV3, ResNet]
    feat_channels: 480 #MobileNetV3-small 288 MobileNetV3-large 480, ResNet 512
  encoder:
    name: rnn
    hidden_dim: 64
  decoder:
    name: 2d-attn
    embedding_size: 64
    hidden_dim_de: 64
    attn_embedding: true
  prediction:
    name: fc
Optimizer:
  name: adam
  lr: 0.0008
  momentum: 0.9
  weight_decay: 0.0
  scheduler: 
    name: step
    milestones_list: [5, 15, 25]
    gamma: 0.1
  warmup: -1
  warmup_lr: 1.0e-06
Train:
  rand_aug: true
  text_aug: true
  balanced_pow: -1
  batch_size: 960
  drop_last: true
  image_shape:
  - 48
  - 160
  shuffle: true
  train_path: /data/remote/ocr_data/OCR_GT/90k_SynthText_SynthAdd.txt
  workers: 32
Val:
  batch_size: 960
  drop_last: true
  image_shape:
  - 48
  - 160
  shuffle: true
  val_path: /data/remote/ocr_data/OCR_GT/openReal/icdar2015_Test.txt
  workers: 32
